services: 
  database:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: cosc349_db
    ports: 
      - "5000:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      
  rest-api:
    build: 
      context: rest-api
      dockerfile: Dockerfile
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: test
      DB_NAME: cosc349_db
      API_PORT: 3000
      CLIENT_PORT: 4000
    ports: 
      - "3000:3000"
    depends_on:
      - database

  frontend:
    build: 
      context: frontend
      dockerfile: Dockerfile
      args:
        API_HOST: http://localhost
        API_PORT: 3000
    ports: 
      - "4000:4200"
    depends_on:
      - rest-api